// Code generated by protoc-gen-go.
// source: fident.proto
// DO NOT EDIT!

/*
Package fident is a generated protocol buffer package.

It is generated from these files:
	fident.proto

It has these top-level messages:
	ServiceRegistrationResult
	ServiceRegistrationPayload
	AuthResult
	AuthChallengeResult
	AuthChallengePayload
	PerformAuthPayload
*/
package fident

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceRegistrationResult struct {
	IdentityID string `protobuf:"bytes,1,opt,name=identityID" json:"identityID,omitempty"`
	ServiceKey string `protobuf:"bytes,2,opt,name=serviceKey" json:"serviceKey,omitempty"`
}

func (m *ServiceRegistrationResult) Reset()                    { *m = ServiceRegistrationResult{} }
func (m *ServiceRegistrationResult) String() string            { return proto.CompactTextString(m) }
func (*ServiceRegistrationResult) ProtoMessage()               {}
func (*ServiceRegistrationResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ServiceRegistrationPayload struct {
	ServiceName   string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	ServiceVendor string `protobuf:"bytes,2,opt,name=serviceVendor" json:"serviceVendor,omitempty"`
	SupportEmail  string `protobuf:"bytes,3,opt,name=supportEmail" json:"supportEmail,omitempty"`
}

func (m *ServiceRegistrationPayload) Reset()                    { *m = ServiceRegistrationPayload{} }
func (m *ServiceRegistrationPayload) String() string            { return proto.CompactTextString(m) }
func (*ServiceRegistrationPayload) ProtoMessage()               {}
func (*ServiceRegistrationPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AuthResult struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *AuthResult) Reset()                    { *m = AuthResult{} }
func (m *AuthResult) String() string            { return proto.CompactTextString(m) }
func (*AuthResult) ProtoMessage()               {}
func (*AuthResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AuthChallengeResult struct {
	Challenge string `protobuf:"bytes,1,opt,name=challenge" json:"challenge,omitempty"`
}

func (m *AuthChallengeResult) Reset()                    { *m = AuthChallengeResult{} }
func (m *AuthChallengeResult) String() string            { return proto.CompactTextString(m) }
func (*AuthChallengeResult) ProtoMessage()               {}
func (*AuthChallengeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type AuthChallengePayload struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *AuthChallengePayload) Reset()                    { *m = AuthChallengePayload{} }
func (m *AuthChallengePayload) String() string            { return proto.CompactTextString(m) }
func (*AuthChallengePayload) ProtoMessage()               {}
func (*AuthChallengePayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PerformAuthPayload struct {
	Username          string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	ChallengeResponse string `protobuf:"bytes,2,opt,name=challengeResponse" json:"challengeResponse,omitempty"`
}

func (m *PerformAuthPayload) Reset()                    { *m = PerformAuthPayload{} }
func (m *PerformAuthPayload) String() string            { return proto.CompactTextString(m) }
func (*PerformAuthPayload) ProtoMessage()               {}
func (*PerformAuthPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*ServiceRegistrationResult)(nil), "fident.ServiceRegistrationResult")
	proto.RegisterType((*ServiceRegistrationPayload)(nil), "fident.ServiceRegistrationPayload")
	proto.RegisterType((*AuthResult)(nil), "fident.AuthResult")
	proto.RegisterType((*AuthChallengeResult)(nil), "fident.AuthChallengeResult")
	proto.RegisterType((*AuthChallengePayload)(nil), "fident.AuthChallengePayload")
	proto.RegisterType((*PerformAuthPayload)(nil), "fident.PerformAuthPayload")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Auth service

type AuthClient interface {
	CreateServiceAccount(ctx context.Context, in *ServiceRegistrationPayload, opts ...grpc.CallOption) (*ServiceRegistrationResult, error)
	GetAuthenticationChallenge(ctx context.Context, in *AuthChallengePayload, opts ...grpc.CallOption) (*AuthChallengeResult, error)
	PerformAuthentication(ctx context.Context, in *PerformAuthPayload, opts ...grpc.CallOption) (*AuthResult, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) CreateServiceAccount(ctx context.Context, in *ServiceRegistrationPayload, opts ...grpc.CallOption) (*ServiceRegistrationResult, error) {
	out := new(ServiceRegistrationResult)
	err := grpc.Invoke(ctx, "/fident.Auth/createServiceAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAuthenticationChallenge(ctx context.Context, in *AuthChallengePayload, opts ...grpc.CallOption) (*AuthChallengeResult, error) {
	out := new(AuthChallengeResult)
	err := grpc.Invoke(ctx, "/fident.Auth/getAuthenticationChallenge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) PerformAuthentication(ctx context.Context, in *PerformAuthPayload, opts ...grpc.CallOption) (*AuthResult, error) {
	out := new(AuthResult)
	err := grpc.Invoke(ctx, "/fident.Auth/performAuthentication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	CreateServiceAccount(context.Context, *ServiceRegistrationPayload) (*ServiceRegistrationResult, error)
	GetAuthenticationChallenge(context.Context, *AuthChallengePayload) (*AuthChallengeResult, error)
	PerformAuthentication(context.Context, *PerformAuthPayload) (*AuthResult, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_CreateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegistrationPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fident.Auth/CreateServiceAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateServiceAccount(ctx, req.(*ServiceRegistrationPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetAuthenticationChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthChallengePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetAuthenticationChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fident.Auth/GetAuthenticationChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetAuthenticationChallenge(ctx, req.(*AuthChallengePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_PerformAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformAuthPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).PerformAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fident.Auth/PerformAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).PerformAuthentication(ctx, req.(*PerformAuthPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fident.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createServiceAccount",
			Handler:    _Auth_CreateServiceAccount_Handler,
		},
		{
			MethodName: "getAuthenticationChallenge",
			Handler:    _Auth_GetAuthenticationChallenge_Handler,
		},
		{
			MethodName: "performAuthentication",
			Handler:    _Auth_PerformAuthentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("fident.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xb5, 0x55, 0x8b, 0x1d, 0xeb, 0xc1, 0xb1, 0x42, 0x5d, 0x8b, 0xd4, 0xc5, 0x83, 0x07, 0xe9,
	0xa1, 0xfd, 0x82, 0xa2, 0x1e, 0x8a, 0x20, 0xa5, 0x82, 0x20, 0x82, 0xb2, 0x6e, 0xa7, 0x6d, 0x30,
	0xdd, 0x0d, 0x9b, 0x8d, 0xd0, 0x3f, 0xf0, 0xe2, 0x3f, 0x6b, 0x92, 0x4d, 0x93, 0xd2, 0x28, 0x1e,
	0xe7, 0xcd, 0x7b, 0x6f, 0x76, 0xde, 0x0e, 0x34, 0xa6, 0xde, 0x84, 0x94, 0xed, 0x06, 0x46, 0x5b,
	0x8d, 0xb5, 0xb4, 0xe2, 0xcf, 0x70, 0xf2, 0x40, 0xe6, 0xc3, 0x93, 0x34, 0xa6, 0x99, 0x17, 0x5a,
	0x23, 0xac, 0xa7, 0xd5, 0x98, 0xc2, 0xc8, 0xb7, 0x78, 0x06, 0x90, 0xb0, 0x3c, 0xbb, 0x1c, 0xde,
	0xb4, 0x2a, 0x9d, 0xca, 0x65, 0x7d, 0x5c, 0x40, 0xe2, 0x7e, 0x98, 0x8a, 0xef, 0x68, 0xd9, 0xaa,
	0xa6, 0xfd, 0x1c, 0xe1, 0x9f, 0x15, 0x60, 0x25, 0xee, 0x23, 0xb1, 0xf4, 0xb5, 0x98, 0x60, 0x07,
	0xf6, 0x1d, 0xf9, 0x5e, 0x2c, 0xc8, 0xf9, 0x17, 0x21, 0xbc, 0x80, 0x03, 0x57, 0x3e, 0x92, 0x9a,
	0x68, 0xe3, 0x66, 0xac, 0x83, 0xc8, 0xa1, 0x11, 0x46, 0x41, 0xa0, 0x8d, 0xbd, 0x5d, 0x08, 0xcf,
	0x6f, 0x6d, 0x27, 0xa4, 0x35, 0x8c, 0x73, 0x80, 0x41, 0x64, 0xe7, 0x6e, 0xb1, 0x26, 0xec, 0x5a,
	0xfd, 0x4e, 0xca, 0xcd, 0x4c, 0x0b, 0xde, 0x87, 0xa3, 0x98, 0x73, 0x3d, 0x17, 0xbe, 0x4f, 0x6a,
	0x46, 0x8e, 0xdc, 0x86, 0xba, 0xcc, 0x20, 0x27, 0xc8, 0x01, 0xde, 0x83, 0xe6, 0x9a, 0x28, 0x5b,
	0x8e, 0xc1, 0x5e, 0xf4, 0xf3, 0x4c, 0x95, 0x6f, 0xb6, 0xaa, 0xf9, 0x0b, 0xe0, 0x88, 0xcc, 0x54,
	0x9b, 0x45, 0x2c, 0xfd, 0x87, 0x02, 0xaf, 0xe0, 0x50, 0x16, 0x9e, 0x15, 0x68, 0x15, 0x92, 0x0b,
	0x63, 0xb3, 0xd1, 0xfb, 0xaa, 0xc2, 0x4e, 0xec, 0x8c, 0xaf, 0xd0, 0x94, 0x86, 0x84, 0x25, 0xf7,
	0x0b, 0x03, 0x29, 0x75, 0xa4, 0x2c, 0xf2, 0xae, 0x3b, 0x86, 0xdf, 0x7f, 0x87, 0x9d, 0xff, 0xc1,
	0x49, 0x93, 0xe1, 0x5b, 0xf8, 0x04, 0x6c, 0x46, 0x36, 0x9e, 0x15, 0x1f, 0x85, 0x4c, 0x9a, 0xab,
	0x28, 0xb0, 0x9d, 0x59, 0x94, 0x25, 0xc4, 0x4e, 0x4b, 0xbb, 0x2b, 0xeb, 0x21, 0x1c, 0x07, 0x79,
	0x48, 0xb9, 0x3d, 0xb2, 0x4c, 0xb7, 0x99, 0x21, 0xc3, 0xa2, 0x67, 0x66, 0xf5, 0x56, 0x4b, 0x6e,
	0xbe, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xe9, 0x29, 0xb3, 0x03, 0x03, 0x00, 0x00,
}
